// swift-tools-version: 5.8

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "Board",
    platforms: [
        .iOS("17.0")
    ],
    products: [
        .iOSApplication(
            name: "Board",
            targets: ["AppModule"],
            bundleIdentifier: "com.nearily.developer",
            teamIdentifier: "Y8DR63X5R9",
            displayVersion: "1.0",
            bundleVersion: "4",
            appIcon: .asset("AppIcon"),
            accentColor: .presetColor(.blue),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            capabilities: [
                .outgoingNetworkConnections()
            ],
            appCategory: .developerTools
        )
    ],
    dependencies: [
        .package(url: "https://github.com/danielsaidi/WebViewKit", "0.4.0"..<"1.0.0")
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            dependencies: [
                .product(name: "WebViewKit", package: "webviewkit")
            ],
            path: "."
        )
    ]
)
